### ISSUE TITLE
Vision & Goals

### ISSUE THREAD

**Issue by torifat** [danieldelcore/mega-interview-guide#18]
First of all, thanks for putting in all that effort and then sharing it with the community ❤️

---

I was thinking about contributing some of the missing bits, although I'm unsure how far I should go with some solutions. And, is my appraoch aligned with your visions and goals for this initiative.

For example, I was looking at _"Verify a prime number?"_. Now the current solution is-

```javascript
const isPrime = (num) => {
  for (let i = 2; i < num; i++) if (num % i === 0) return false;

  return num > 1;
};
```

There are a few things we can do here:
1. Replace this version with a bit efficient version.
2. Add a step-by-step example of how we can improve it.
3. Replace this version with the most efficient version.
4. Add external resources.

Keen to know your thoughts. Which one would you prefer?

----
#### Here's a version I'm fiddling with now:

The simplest approach is to check if num is divisible by every integer less than num.

```javascript
const isPrime = (num) => {
  for (let i = 2; i < num; i++) if (num % i === 0) return false;

  return num > 1;
};
```

A more efficient approach is to check if the num is divisible by every integer up to its square root.

> **Should we explain why one of the factors should always be less or equal to the square root of a number?**

```javascript
const isPrime = (num) => {
  const limit = Math.sqrt(num);
  for (let i = 2; i <= limit; i++) if (num % i === 0) return false;

  return num > 1;
};
```

A slightly more efficient approach is also to avoid all even numbers since they are divisible by 2; hence can't be prime.

```javascript
const isPrime = (num) => {
  if (num % 2 === 0) return num === 2;
  const limit = Math.sqrt(num);
  for (let i = 3; i <= limit; i+=2) 
      if (num % i === 0) return false;
  return num > 1;
};
```

We can keep creating slightly more efficient versions by eliminating multiples of known primes.
> 1. **Should we explain how they can derive this from `6k + i` or even write more efficient versions following the same pattern `(p1 * p2 * ... * pn)k + i`?**

```javascript
const isPrime = (num) => {
  if (num % 2 === 0) return num === 2;
  if (num % 3 === 0) return num === 3;
  const limit = Math.sqrt(num);
  for (let i = 5; i <= limit; i+=6) 
      if (num % i === 0 || num % (i + 2) === 0) return false;
  return num > 1;
};
``` 

---
Here's the result of [not very scientific benchmark](https://jsben.ch/KdZ7W) I did 😅

<img width="793" alt="Screen Shot 2021-07-21 at 6 55 55 pm" src="https://user-images.githubusercontent.com/208544/126461414-b2151e2d-ca5d-49e7-b1af-21844803a1c2.png">

**Comment by danieldelcore** [comment]
Woah thanks for putting this issue together, I really appreciate you jumping in!

> is my approach aligned with your visions and goals for this initiative.

In general my goals for this project are quite relaxed, I'd be more than happy for yourself and the wider community to shape it into whatever we want it to be 😀! Feel free to throw up a PR if you see something you want to improve 😄!

I really like your approach in particular because it provides a base solution and gives readers an opportunity to understand why the solution works and how it could be improved upon. 

> There are a few things we can do here:
> 1. Replace this version with a bit efficient version.
> 1. Add a step-by-step example of how we can improve it.
> 1. Replace this version with the most efficient version.
> 1. Add external resources.

I like all of the above!

For the purposes of this project one callout i'd make is to be conscious that the audience may be relatively new to the industry, so for that reason, I'm less worried about always having the most performant code and more worried about examples that can be easily understood so the reader can digest and understand them enough to then be able to take those learnings to an interview with them without the need to heavily memorize. Performance for example can sometimes be taken to extremes that are in some ways hard to comprehend or reason about. So just keep that in mind if you're finding that you're trading off one over the other.  But as long as it is easily understood i'd be happy to go in either direction 😄!

Otherwise, what you've suggested is great! I think the examples and explanations are really good and they build up really nicely!

Thanks again for getting involved!
Cheers!

**Comment by torifat** [comment]
> I'm less worried about always having the most performant code and more worried about examples that can be easily understood so the reader can digest and understand them enough to then be able to take those learnings to an interview with them without the need to heavily memorize

💯 Totally agree!

I will raise a PR soon 🤞🏽

**Comment by danieldelcore** [comment]
Amazing thanks so much! I'll have a look now!
